version: '3.4'
volumes:
<<<<<<< HEAD
  fluent_data:
services:
  postgresdb:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - fluent_data:/var/lib/postgresql/data
  fluentone:
    image: fluent_api 
    ports:
      - "5000:80"
    depends_on:
      - postgresdb
    environment:
      - HOST=${HOST}
      - USER_ID=${USER_ID}
      - USER_PASSWORD=${POSTGRES_PASSWORD}
      - PORT=80
=======
 fluent_data:
>>>>>>> cdb857f389c03c123957a71dc90c5302739064cf

services: 
 postgresdb:
  image: postgres:alpine
  environment:
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  ports:
   - "5432:5432"
  volumes:
   - fluent_data:/var/lib/postgresql/data
  
 fluentone:
  image: fluent_api 
  ports:
   - "5000:80"
  depends_on:
   - postgresdb
  environment:
   - HOST=${HOST}
   - USER_ID=${USER_ID}
   - USER_PASSWORD=${POSTGRES_PASSWORD}
   - PORT=80
    
 fluenttwo:
  image: fluent_api 
  ports:
   - "5001:80"
  depends_on:
   - postgresdb
  environment:
   - HOST=${HOST}
   - USER_ID=${USER_ID}
   - USER_PASSWORD=${POSTGRES_PASSWORD}
   - PORT=80
      
 fluentthree:
  image: fluent_api 
  ports:
   - "5002:80"
  depends_on:
   - postgresdb
  environment:
   - HOST=${HOST}
   - USER_ID=${USER_ID}
   - USER_PASSWORD=${POSTGRES_PASSWORD}
   - PORT=80
      
 fluentfour:
  image: fluent_api 
  ports:
   - "5003:80"
  depends_on:
   - postgresdb
  environment:
   - HOST=${HOST}
   - USER_ID=${USER_ID}
   - USER_PASSWORD=${POSTGRES_PASSWORD}
   - PORT=80

 nginx: 
  image: nginx
  ports: 
   - "80:80"
   - "443:443"
  depends_on: 
   - fluentone
   - fluenttwo
   - fluentthree
   - fluentfour
   - postgresdb
  volumes: 
   - ./static:/public_html
   - ./nginx.conf:/etc/nginx/nginx.conf
   - ./dhparam:/etc/nginx/dhparam
   - ./certbot/conf:/etc/nginx/ssl
   - ./certbot/data:/usr/share/nginx/html/letsencrypt
