version: '3'
volumes:
  fluent_data: 
services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes: 
      - fluent_data:/var/lib/postgresql/data
  fluentmessengerapi:
    build: '.'
    ports:
      - "8080:80"
    depends_on: 
      - postgresdb
    environment:
      - HOST=${HOST}
      - USER_ID=${USER_ID}
      - USER_PASSWORD=${POSTGRES_PASSWORD}
  